config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:create, :new]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, uniqueness: { scope: :ingredient }
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>All cocktails</h1>
      <ul class="list-group">
        <% @cocktails.each do |cocktail| %>
          <li class="list-group-item">
            <%= link_to cocktail.name, cocktail_path(cocktail) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Create a new cocktail</h1>

      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://wisk.ai/wp-content/uploads/2019/07/liquor-inventory-scale-2.jpg);">
  <div class="container">
    <h1><%= @cocktail.name %></h1>
    <p>Hell of a cocktail!</p>
  </div>
</div>

<div class="container overlap text-align-center">

  <div class="card  align-middle m-3 w-100" style="width: 18rem;">
    <!-- Contains the info about restaurant -->
    <div class="card-body">
      <h3 class="card-title"><%= @cocktail.name %></h5>
      <p class="card-text">Recipe</p>
    </div>
  </div>

  <div class="card align-middle m-3 w-100" style="width: 18rem;">
    <!-- Contains the info about restaurant -->
    <div class="card-body">
      <h3 class="card-title">Info</h3>
      <p class="card-text">Description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi temporibus facilis id nemo aperiam sunt optio doloremque ducimus minus pariatur, tempore numquam dolorum autem culpa ea voluptatum aspernatur, molestiae repellat.</p>
      <% dose = 0 %>
      <% @doses.each do |dose| %>
        <p>
          <%= dose.description %> of <%= dose.ingredient.name %>.
          <%= link_to "Delete", dose_path(dose.id), method: "delete", :class => "btn btn-danger" %>
        </p>
      <% end %>
      <h4><%= link_to "Add doses", new_cocktail_dose_path(@cocktail) %></h4>

     <!--  <%#= simple_form_for [@cocktail, @dose] do |f| %>
        <%#= f.input :description%>
        <%#= f.association :ingredient %>
        <%#= f.submit%>
      <%# end %> -->

      <p class="card-text"><i class="fas fa-euro-sign"></i>15</p>
      <%= link_to 'Back', cocktails_path, :class => "btn btn-primary" %> |
  </div>

</div>

app/views/doses/new.html.erb
<h3>Add a new dose</h3>
<%= simple_form_for [cocktail, dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>